version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/sources"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/distribution/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
