cask "font-pocketgull" do
  version "3.1.0"
  sha256 "980077e342aa54ecd48e074d666b26230babd86667af2b0468ad411f352b00fe"

  url "https://github.com/pocketgull-app/pocketgull-font/releases/download/v#{version}/pocketgull-font-v#{version}.zip",
      verified: "github.com/pocketgull-app/pocketgull-font/"
  name "PocketGull"
  desc "Humanist sans-serif, display, slab, and telemetry monospace font superfamily"
  homepage "https://font.pocketgull.app"

  font "fonts/ttf/PocketGull-Black.ttf"
  font "fonts/ttf/PocketGull-Bold.ttf"
  font "fonts/ttf/PocketGull-BoldItalic.ttf"
  font "fonts/ttf/PocketGull-Chiseltip.ttf"
  font "fonts/ttf/PocketGull-CondensedBold.ttf"
  font "fonts/ttf/PocketGull-Fineliner.ttf"
  font "fonts/ttf/PocketGull-Halftone.ttf"
  font "fonts/ttf/PocketGull-Inline.ttf"
  font "fonts/ttf/PocketGull-Italic.ttf"
  font "fonts/ttf/PocketGull-MarkerRaw.ttf"
  font "fonts/ttf/PocketGull-Micro.ttf"
  font "fonts/ttf/PocketGull-Outline.ttf"
  font "fonts/ttf/PocketGull-Regular.ttf"
  font "fonts/ttf/PocketGull-Serif-Bold.ttf"
  font "fonts/ttf/PocketGull-Serif-Regular.ttf"
  font "fonts/ttf/PocketGull-Slab-Bold.ttf"
  font "fonts/ttf/PocketGull-Slab-Regular.ttf"
  font "fonts/ttf/PocketGull-Math.ttf"
  font "fonts/ttf/PocketGull-Chem.ttf"
  font "fonts/ttf/PocketGull-Genome.ttf"
  font "fonts/ttf/PocketGull-Music.ttf"
  font "fonts/ttf/PocketGull-Algo.ttf"
  font "fonts/ttf/PocketGull-Learn.ttf"
  font "fonts/ttf/PocketGull-Lab.ttf"
  font "fonts/ttf/PocketGull-Press.ttf"
  font "fonts/ttf/PocketGull-Soft.ttf"
  font "fonts/ttf/PocketGull-Soft-Bold.ttf"
  font "fonts/ttf/PocketGull-Soft-Regular.ttf"
  font "fonts/ttf/PocketGull-VF.ttf"
  font "fonts/ttf/PocketGullMono-Bold.ttf"
  font "fonts/ttf/PocketGullMono-Italic.ttf"
  font "fonts/ttf/PocketGullMono-Regular.ttf"

  # No zap stanza required
end
